version: 2.1

orbs:
  node: circleci/node@7.0.0

parameters:
  node_version:
    type: string
    default: '22.13.0'

commands:
  install_deps:
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - node/install-packages:
          pkg-manager: yarn
          with-cache: false
          app-dir: ~/repo
          override-ci-command: yarn install --pure-lockfile --no-progress

jobs:
  build:
    executor:
      name: node/default
      tag: << pipeline.parameters.node_version >>
    working_directory: ~/repo
    steps:
      - checkout
      - install_deps
      - run: yarn test
      - run: yarn build
      - run: yarn lint:ci
